---
title: "Fire risk in Greater London"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
---

```{r setup}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(rgdal)
library(rgeos)
library(maptools)
library(RColorBrewer)
library(leaflet)

```

```{r global}
# load data in 'global' chunk so it can be shared by all users of the dashboard

# create borough map
london_shp <- readShapePoly("../statistical-gis-boundaries-london/ESRI/London_Borough_Excluding_MHW.shp")
london_map <- fortify(london_shp)
london_map <- rename(london_map, Easting_rounded = long, Northing_rounded = lat)

# load fire data
map.data <- readRDS("../Data/mapData4.rds")

# load fire data
fires <- as_tibble(readRDS("../Data/fires2.rds"))
fires$PropertyCategory <- factor(fires$PropertyCategory)
N <- nrow(fires)

# if (input$propCats != "All"){
#   fires <- subset(fires, PropertyCategory == input$propCats)
# }

# convert
d <- fires
d$d_ID <- 1:nrow(d)

# Create coordinates variable
coords <- cbind(Easting_rounded = as.numeric(as.character(d$Easting_rounded)),
                Northing_rounded = as.numeric(as.character(d$Northing_rounded)))

# CRS
ukgrid = "+init=epsg:27700"
latlong = "+init=epsg:4326"

# Create the SpatialPointsDataFrame
d_SP <- SpatialPointsDataFrame(coords, 
                               data = data.frame(d$IncidentNumber, d$d_ID, d$PropertyCategory), 
                               proj4string = CRS(ukgrid))

d_SP_LL <- spTransform(d_SP, CRS(latlong))
# we also need to rename the columns
colnames(d_SP_LL@coords)[colnames(d_SP_LL@coords) == "Easting_rounded"] <- "Longitude"
colnames(d_SP_LL@coords)[colnames(d_SP_LL@coords) == "Northing_rounded"] <- "Latitude"

# load ward map data
lnd.res <- readShapePoly("../London-wards-2014/London-wards-2014_ESRI/London_Ward_CityMerged.shp")
lnd.res.map <- fortify(lnd.res, region = "GSS_CODE")

```


Sidebar {.sidebar}
=====================================

### Date range

```{r}
dateRangeInput("date_range", label = NULL,
               start = "2015-01-01",
               end = "2015-08-31")

```

### Property Categories

```{r}
radioButtons("propCats", label = NULL,
             choices = list("All" = "All", 
                            "Dwelling" = "Dwelling", 
                            "Non Residential" = "Non Residential",
                            "Other Residential" = "Other Residential", 
                            "Road Vehicle" = "Road Vehicle"),
             selected = "All"
)

```



Simple plots
=====================================

Row {data-height=700} 
-----------------------------------------------------------------------

### Map of fire locations - Jan 2012 to Aug 2015 

```{r}
renderPlot({
    
    
    
    if (input$propCats != "All"){
      fires <- subset(fires, PropertyCategory == input$propCats)
    } 
    
    
    # build base ggplot object
    p <- ggplot(data=fires, aes(x=Easting_rounded, y=Northing_rounded)) + 
      xlab("") + ylab("") + 
      theme_void() +
      theme(axis.ticks = element_blank(), axis.text.y = element_blank(), axis.text.x = element_blank())
    
    # depending on user input choice, draw correct plot
    if (input$colour == "op1") {
      p + stat_bin2d(bins=input$bins) + 
        scale_fill_gradient(low="skyblue", high="red") + 
        geom_path(data=london_map, aes(x = Easting_rounded, y = Northing_rounded, group=group)) # + 
      # ggtitle("Heatmap of 2D bin count")
      
    }
    else if (input$colour == "op2") {
      p + stat_bin2d(aes(fill=log10(..count..)), bins=input$bins) + 
        scale_fill_gradient(low="skyblue", high="red") + 
        geom_path(data=london_map, aes(x = Easting_rounded, y = Northing_rounded, group=group)) # + 
      # ggtitle("Heatmap of 2D bin count - log scale")
    }
    else if (input$colour == "op3") {
      
      # Color palette for the KDE plot
      rf <- colorRampPalette(rev(brewer.pal(11,'Spectral')))
      r <- rf(32)
      
      p + stat_density_2d(aes(fill=..level..), geom = "polygon", n=input$bins) +
        scale_fill_gradientn(colours=r) + 
        geom_path(data=london_map, aes(x = Easting_rounded, y = Northing_rounded, group=group)) + guides(fill=FALSE)
      # ggtitle("2D kernel density estimation") 
    }
    else {
      ggplot(london_map, aes(x = Easting_rounded, y = Northing_rounded, group=group)) + geom_path() + 
        geom_point(data=fires, aes(x=Easting_rounded, y=Northing_rounded, group=NULL), alpha=0.02 * (N / nrow(fires)), colour = "red") + 
        theme_void() +
        xlab("") + ylab("") +
        theme(axis.ticks = element_blank(), axis.text.y = element_blank(), axis.text.x = element_blank()) # +
      # ggtitle("Map of fires in London")
    }
    
  })


```


Row {data-height=300}
-----------------------------------------------------------------------

### options

```{r}
### Type of plot:

radioButtons("colour", label = NULL,
                          c("Simple map" = "d", 
                            "Heatmap of 2D bin count" = "op1",
                            "Heatmap of 2D bin count - log scale" = "op2",
                            "2D kernel density estimation" = "op3")
             )
```

### Number of bins (for Heatmap):

```{r}
sliderInput("bins", 
                         # h4("Number of bins (for Heatmap):"),
            label = NULL,
                         min = 1,
                         max = 200,
                         value = 100
            )
      

```


Ward model
=====================================

Row {data-height=650}
-----------------------------------------------------------------------

### Fire risk model quartiles by electoral ward

```{r}
renderPlot({
    
    
  
  # calculte fire risk based on input weights
  map.data$fr <- (input$w1 * map.data$ct_fires.d + input$w2 * 
                    map.data$av_workTime.d + input$w3 * 
                    map.data$ct_fires.nr + input$w4 * map.data$ct_fires.or + 
                    input$w5 * map.data$ct_fires.v) / 
    sum(input$w1, input$w2, input$w3, input$w4, input$w5, na.rm = T)
  
  # create quartiles
  map.data$quartile[!is.na(map.data$fr)] <- ntile(map.data$fr[!is.na(map.data$fr)], 4)
  map.data$quartile <- ordered(map.data$quartile)
  
  lnd.res.map <- merge(lnd.res.map, map.data, by.x = "id", by.y = "GSS_CODE", all.x = T)
  
  # create colour palette
  pal <- colorRampPalette(c("white", "red"))(4)
  
  # draw ward plot
  
  ggplot(lnd.res.map, aes(x=long, y=lat, group=group, fill=quartile)) + #
    geom_polygon(colour="black") + 
    scale_fill_manual(values=pal) +
    xlab("") + ylab("") + 
    theme_minimal() +
    labs(fill="Fire risk\nQuartile") +
    theme(axis.ticks = element_blank(), axis.text.y = element_blank(), 
          axis.text.x = element_blank(), panel.background = element_blank(),
          panel.grid = element_blank())

    })
```

Row {data-height=350}
-----------------------------------------------------------------------

### Model parameters
```{r}
numericInput("w1", 
             label = h4("Dwelling fire weight"), 
             value = 3
)

numericInput("w3", 
             label = h4("Non-residential fire weight"), 
             value = 1
)

```

### Model parameters
```{r}
numericInput("w5", 
             label = h4("Vehicle fire weight"), 
             value = 1
)

numericInput("w2", 
             label = h4("Dwelling fire severity weight"), 
             value = 3
)

```

### Model parameters
```{r}

numericInput("w4", 
             label = h4("Other residential fire weight"), 
             value = 1
)

```

Leaflet cluster map
=====================================

### Map of fires

```{r}

renderLeaflet({
  
leaflet() %>%
  addTiles() %>%
  addMarkers(lng=d_SP_LL@coords[,1], 
             lat=d_SP_LL@coords[,2], 
             popup=d_SP_LL@data$d.PropertyCategory,
  clusterOptions = markerClusterOptions()
)
})

```


Leaflet circle map
=====================================

### Map of fires

```{r}
# if (input$propCats != "All"){
#   fires <- subset(fires, PropertyCategory == input$propCats)
# }

renderLeaflet({
  
leaflet() %>%
  addTiles() %>%
  addCircleMarkers(
    lng=d_SP_LL@coords[,1], 
    lat=d_SP_LL@coords[,2],
    radius = 2,
    color = "red",
    stroke = FALSE, fillOpacity = 0.1,
    popup=d_SP_LL@data$d.PropertyCategory
  )
  
})

```
